# 开发环境配置
app:
  name: "server"
  version: "1.0.0"
  mode: "dev"
  port: 8080
  # AES密钥用于加密敏感数据（如云厂商密钥、主机密码等）
  # 开发环境使用固定密钥，生产环境必须更换为随机生成的32字节密钥
  # 密钥必须是16、24或32字节长度，这里使用32字节
  aes_key: "dev_aes_key_32_bytes_for_test_12"

# 数据库配置
database:
  type: "mysql"
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "123456"
    #database: "gin-devops"
    database: "devops-asset"
    charset: "utf8mb4"
    parseTime: true
    loc: "Local"

# Redis配置
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0

# JWT配置
jwt:
  secret: "CvXPiv34e2474LC5Xj7IP"
  expiration: "12h"

# 日志配置
log:
  level: "debug"
  maxSize: 50
  maxBackups: 3
  maxAge: 30
  compress: true

# 管理员配置
admin:
  password: "123456"
  salt: "rHECMvW3el1zhpdzgx9dY"

# 注册配置
registration:
  enabled: true          # 开发环境开启注册功能
  require_approval: false # 开发环境不需要审批
  default_role_id: 2     # 默认普通用户角色

# 分页配置
pagination:
  defaultPage: 1
  defaultPageSize: 20
  maxPageSize: 100 
