# 开发环境配置
app:
  name: "server"
  version: "1.0.0"
  mode: "dev"
  port: 8080

# 数据库配置
database:
  type: "mysql"
  mysql:
    host: "localhost"
    port: 3306
    username: "root"
    password: "123456"
    database: "gin-devops"
    charset: "utf8mb4"
    parseTime: true
    loc: "Local"

# Redis配置
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0

# JWT配置
jwt:
  secret: "CvXPiv34e2474LC5Xj7IP"
  expiration: "12h"

# 日志配置
log:
  level: "debug"
  maxSize: 50
  maxBackups: 3
  maxAge: 30
  compress: true

# 管理员配置
admin:
  password: "123456"
  salt: "rHECMvW3el1zhpdzgx9dY"

# 分页配置
pagination:
  defaultPage: 1
  defaultPageSize: 20
  maxPageSize: 100 